// <auto-generated />
using System;
using ApiFestaJulina.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiFestaJulina.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ApiFestaJulina.Models.Eventos", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_evento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEvento"));

                    b.Property<bool?>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("local");

                    b.Property<string>("NomeEvento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome_evento");

                    b.Property<int>("Qtde_Ingressos")
                        .HasColumnType("int")
                        .HasColumnName("qtde_ingressos");

                    b.Property<int>("Qtde_Lotes")
                        .HasColumnType("int")
                        .HasColumnName("qtde_lotes");

                    b.HasKey("IdEvento");

                    b.ToTable("evento");
                });

            modelBuilder.Entity("ApiFestaJulina.Models.Ingressos", b =>
                {
                    b.Property<int>("IdIngresso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ingresso");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdIngresso"));

                    b.Property<DateTime?>("DtEntrada")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dt_entrada");

                    b.Property<int>("IdLote")
                        .HasColumnType("int")
                        .HasColumnName("id_lote");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    b.Property<int>("IdStatusValidacao")
                        .HasColumnType("int")
                        .HasColumnName("id_status_validacao");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("QrCode")
                        .HasColumnType("longtext")
                        .HasColumnName("qr_code");

                    b.Property<int?>("UsuarioQueLeu")
                        .HasColumnType("int")
                        .HasColumnName("usuario_que_leu");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor");

                    b.HasKey("IdIngresso");

                    b.HasIndex("IdLote");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Ingressos");
                });

            modelBuilder.Entity("ApiFestaJulina.Models.Lotes", b =>
                {
                    b.Property<int>("IdLote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_lote");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdLote"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dta_criacao");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dta_fechamento");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.Property<int>("IdEvento")
                        .HasColumnType("int")
                        .HasColumnName("id_evento");

                    b.Property<int>("QtdeIngressosLotes")
                        .HasColumnType("int")
                        .HasColumnName("qtde_ingressos_lotes");

                    b.Property<int>("Saldo")
                        .HasColumnType("int")
                        .HasColumnName("saldo");

                    b.Property<int>("TipoLote")
                        .HasColumnType("int")
                        .HasColumnName("tipo_lote");

                    b.Property<decimal>("ValorIng")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_ing");

                    b.HasKey("IdLote");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("ApiFestaJulina.Models.Pedidos", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<DateTime?>("DtaFechamento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dta_fechamento");

                    b.Property<DateTime?>("DtaReserva")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dta_reserva");

                    b.Property<string>("FtComprovante")
                        .HasColumnType("longtext")
                        .HasColumnName("ft_comprovante");

                    b.Property<int>("IdStatus")
                        .HasColumnType("int")
                        .HasColumnName("id_status");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade");

                    b.Property<int>("TipoPagamento")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_pagamento");

                    b.Property<int?>("UltimaAcaoPor")
                        .HasColumnType("int")
                        .HasColumnName("ultima_acao_por");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor");

                    b.HasKey("IdPedido");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("ApiFestaJulina.Models.Perfil", b =>
                {
                    b.Property<int>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_perfil");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPerfil"));

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.HasKey("IdPerfil");

                    b.ToTable("Perfil");
                });

            modelBuilder.Entity("ApiFestaJulina.Models.Perguntas", b =>
                {
                    b.Property<int>("IdPergunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pergunta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPergunta"));

                    b.Property<string>("DescricaoPergunta")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descricao_pergunta");

                    b.Property<int>("IdTpUser")
                        .HasColumnType("int")
                        .HasColumnName("id_tp_user");

                    b.Property<int>("TipoPergunta")
                        .HasColumnType("int")
                        .HasColumnName("tp_pergunta");

                    b.HasKey("IdPergunta");

                    b.ToTable("Perguntas");
                });

            modelBuilder.Entity("ApiFestaJulina.Models.Resposta", b =>
                {
                    b.Property<int>("IdResposta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_resposta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdResposta"));

                    b.Property<DateTime?>("DtResposta")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_resposta");

                    b.Property<int>("IdPergunta")
                        .HasColumnType("int")
                        .HasColumnName("id_pergunta");

                    b.Property<string>("resposta")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("resposta");

                    b.HasKey("IdResposta");

                    b.ToTable("Respostas");
                });

            modelBuilder.Entity("ApiFestaJulina.Models.Sessao", b =>
                {
                    b.Property<int>("IdSessao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sessao");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSessao"));

                    b.Property<bool?>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_inicio");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Token")
                        .HasColumnType("longtext")
                        .HasColumnName("token");

                    b.HasKey("IdSessao");

                    b.HasIndex("IdUsuario");

                    b.ToTable("sessao");
                });

            modelBuilder.Entity("ApiFestaJulina.Models.Tipo", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTipo"));

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.HasKey("IdTipo");

                    b.ToTable("Tipo");
                });

            modelBuilder.Entity("ApiFestaJulina.Models.TipoUsuario", b =>
                {
                    b.Property<int>("IdTpUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tp_user");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTpUsuario"));

                    b.Property<string>("DescricaoTpUser")
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.HasKey("IdTpUsuario");

                    b.ToTable("TipoUsuario");
                });

            modelBuilder.Entity("ApiFestaJulina.Models.Usuarios", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int")
                        .HasColumnName("id_perfil");

                    b.Property<string>("ImagemPerfil")
                        .HasColumnType("longtext")
                        .HasColumnName("imagem_perfil");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<string>("NovaSenhaTemporaria")
                        .HasColumnType("longtext")
                        .HasColumnName("nova_senha_temporaria");

                    b.Property<bool>("PossuiDeficiencia")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("possui_deficiencia");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("senha");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext")
                        .HasColumnName("telefone");

                    b.Property<string>("TipoDeficiencia")
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_deficiencia");

                    b.Property<DateTime?>("TokenExpiracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("token_expiracao");

                    b.Property<string>("TokenRecuperacaoSenha")
                        .HasColumnType("longtext")
                        .HasColumnName("token_recuperacao_senha");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdPerfil");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ApiFestaJulina.Models.Ingressos", b =>
                {
                    b.HasOne("ApiFestaJulina.Models.Lotes", "Lote")
                        .WithMany("Ingressos")
                        .HasForeignKey("IdLote")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiFestaJulina.Models.Pedidos", "Pedido")
                        .WithMany("Ingressos")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiFestaJulina.Models.Usuarios", "Usuario")
                        .WithMany("Ingressos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");

                    b.Navigation("Pedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiFestaJulina.Models.Sessao", b =>
                {
                    b.HasOne("ApiFestaJulina.Models.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiFestaJulina.Models.Usuarios", b =>
                {
                    b.HasOne("ApiFestaJulina.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("ApiFestaJulina.Models.Lotes", b =>
                {
                    b.Navigation("Ingressos");
                });

            modelBuilder.Entity("ApiFestaJulina.Models.Pedidos", b =>
                {
                    b.Navigation("Ingressos");
                });

            modelBuilder.Entity("ApiFestaJulina.Models.Usuarios", b =>
                {
                    b.Navigation("Ingressos");
                });
#pragma warning restore 612, 618
        }
    }
}
